name: "Publish Application"

on:
  workflow_dispatch:
    inputs:
      git_branch:
        required: true
        type: string
        default: master

jobs:
  app_build:
    name: 'Application build'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3

      - name: Provide WASM Tools
        run: dotnet workload install wasm-tools

      - name: Publish
        run: |
          cd Fleury
          dotnet publish Fleury.csproj -c Release -o app

      - name: Deploy into Github Actions
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.PAT_GITHUB }}
            publish_branch: gh-pages
            publish_dir: app/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true

